### PR TITLE
Add druid-basic-security extension

### PR DESCRIPTION
**Pull request by jon-wei**

### CODE REVIEW

**Comment by a2l007** [comment]
Hello, I'm trying to test the druid-kerberos extension based out of https://github.com/druid-io/druid/pull/4271 but I keep getting the following JsonMapping exception: 
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Could not resolve type id 'kerberos' into a subtype of [simple type, class io.druid.server.security.Authenticator]
 at [Source: N/A; line: -1, column: -1]

from   at io.druid.server.initialization.AuthenticatorMapperModule.configure(AuthenticatorMapperModule.java:60) 
Are there any other properties I need to set apart from the following?
druid.auth.authenticatorChain=["KerberosAuthenticator"]
druid.auth.authenticator.KerberosAuthenticator.type=kerberos
druid.auth.escalatedAuthenticator="KerberosAuthenticator"
druid.auth.authorizers=["KerberosAuthenticator"]
druid.extensions.loadList=["druid-kerberos"]

**Comment by jon-wei** [comment]
@a2l007 

```
druid.auth.authenticatorChain=["KerberosAuthenticator"]
druid.auth.authenticator.KerberosAuthenticator.type=kerberos
druid.auth.escalatedAuthenticator="KerberosAuthenticator"
druid.extensions.loadList=["druid-kerberos"]
```

This is enough to load the kerberos authenticator, although there are some other parameters like keytab and authorizerName that you'll need to set. From your log it looks like it is trying to instantiate a kerberos authenticator.

Maybe check that your extensions directory has the kerberos module and also check that the version is up-to-date.

```
druid.auth.authorizers=["KerberosAuthenticator"]
```

This part won't work, the authorizers are separate from the authenticators and the kerberos module doesn't provide an authorizer.

You can leave that line blank (it'll default to an `allowAll` authorizer) and point the kerberos authenticator to it with `druid.auth.authenticator.KerberosAuthenticator.authorizerName=allowAll`

**Comment by a2l007** [comment]
Yeah druid-kerberos module is up to date. I'll investigate further to see what could be going wrong.

**Comment by a2l007** [comment]
Hello Jon,
In the case of unsecured paths such as /console.html, what is the responsibility of the custom Authenticator ?
Presently, an authenticator implementation wouldn't know that it is an unsecured path and therefore fails to authenticate the request. Even though an AUTHORIZATION_CHECKED flag is assigned to the request by the UnsecuredResourceFilter, PreResponseAuthorizationCheckFilter identifies this an unauthenticated request as none of the Authenticators failed to authenticate that request. So I was wondering does the authenticator implementation have to do an explicit check whether the request is one among the unsecured paths?

**Comment by jon-wei** [comment]
@a2l007

The "UnsecuredResourceFilrer" probably needs a better name, it's there to pass authorization checks for static resources like console.html; this filter runs after all of the Authenticator provided filters, so a custom Authenticator should still authenticate those requests as normal

**Comment by a2l007** [comment]
@jon-wei thanks for clarifying. So if a custom authenticator successfully authenticates such a request, what should it attach to the Druid-Authentication-Result attribute, given the fact that Druid Authorization Checked attribute is added by the UnsecuredResouceFilter anyways?

**Pull request closed without merging**
